Update webpack.base.config.js
遇到如下错误
```
Entry module not found: Error: Can't resolve 'babel' in 'v2ex_frontend-master'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
```

and
```
[Vue warn]: Vue is a constructor and should be called with the `new` keyword
./src/components/App.vue
Module build failed: TypeError: this._init is not a function
```